name: credo
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1


environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  font_awesome_flutter: ^10.5.0
  http: ^1.3.0
  audioplayers: ^6.3.0
  fluttertoast: ^8.2.12
  flutter_native_contact_picker: ^0.0.4
  image_picker: ^1.1.2
  flutter_sound: ^9.25.4
  http_parser: ^4.1.2
  url_launcher: ^6.3.1
  cached_network_image: ^3.4.1
  push: ^3.3.3
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  lottie: ^3.3.1
  firebase_messaging: ^15.2.4
  flutter_dotenv: ^5.2.1
  flutter_local_notifications: ^18.0.1
  shared_preferences: ^2.5.2
  another_flushbar: ^1.12.30
  share_plus: ^10.1.4
  local_auth: ^2.3.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  connectivity_plus: ^6.1.3
  app_settings: ^5.2.0
  dart_jsonwebtoken: ^3.2.0
  json_annotation: ^4.9.0
  googleapis_auth: ^1.6.0
  firebase_analytics: ^11.4.4
  cloud_firestore: ^5.6.5
  path_provider: ^2.1.5
  permission_handler: ^11.4.0
  image: ^4.5.3
  record: ^5.2.1
  just_audio: ^0.9.46
  flutter_bloc: ^9.1.0
  auto_size_text: ^3.0.0
  flutter_pdfview: ^1.4.0
  pdf: ^3.11.3
  printing: ^5.14.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_utils: ^2.8.10
  build_runner: 2.4.15
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.5
  change_app_package_name: ^1.5.0

dependency_overrides:
  characters: ^1.4.0
  collection: ^1.19.1
  material_color_utilities: ^0.12.0
  meta: ^1.16.0
  async: ^2.12.0
  boolean_selector: ^2.1.2
  flutter_lints: ^5.0.0
  clock: ^1.1.2
  fake_async: ^1.3.2
  leak_tracker: ^10.0.8
  leak_tracker_flutter_testing: ^3.0.9
  matcher: ^0.12.17
  path: ^1.9.1
  source_span: ^1.10.1
  stack_trace: ^1.12.1
  stream_channel: ^2.1.3
  string_scanner: ^1.4.1
  term_glyph: ^1.2.2
  test_api: ^0.7.4
  vm_service: ^15.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/business_types/
    - assets/images/business_categories/
    - assets/images/black_logo/
    - assets/images/white_logo/
    - assets/sounds/
    - assets/animation/
    - assets/fonts/
  
  fonts:
    - family: SF-Pro
      fonts:
        - asset: assets/fonts/SF-Pro-Italic.ttf
        - asset: assets/fonts/SF-Pro-Text-Regular.otf
        - asset: assets/fonts/SF-Pro.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/play_store_512.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/play_store_512.png"
