// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk7PKdc98dW7kh5vIYR3ZFEO_mpGBGLjI',
    appId: '1:618269514387:web:1a83834ee229d935240b66',
    messagingSenderId: '618269514387',
    projectId: 'pushnotifications-00001',
    authDomain: 'pushnotifications-00001.firebaseapp.com',
    storageBucket: 'pushnotifications-00001.firebasestorage.app',
    measurementId: 'G-M2FSEHKQ3Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1Lu7W_2XQnZRUUl4qjkb5Y9M-Qp_O46w',
    appId: '1:618269514387:android:130abcc8873e43a6240b66',
    messagingSenderId: '618269514387',
    projectId: 'pushnotifications-00001',
    storageBucket: 'pushnotifications-00001.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQp2M-uQ0vSQhsrz9khotj8aiCHXc3WpQ',
    appId: '1:618269514387:ios:29bcd22049cb1293240b66',
    messagingSenderId: '618269514387',
    projectId: 'pushnotifications-00001',
    storageBucket: 'pushnotifications-00001.firebasestorage.app',
    iosBundleId: 'com.credolabs.credo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQp2M-uQ0vSQhsrz9khotj8aiCHXc3WpQ',
    appId: '1:618269514387:ios:29bcd22049cb1293240b66',
    messagingSenderId: '618269514387',
    projectId: 'pushnotifications-00001',
    storageBucket: 'pushnotifications-00001.firebasestorage.app',
    iosBundleId: 'com.credolabs.credo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBk7PKdc98dW7kh5vIYR3ZFEO_mpGBGLjI',
    appId: '1:618269514387:web:bbbe49c83ce06481240b66',
    messagingSenderId: '618269514387',
    projectId: 'pushnotifications-00001',
    authDomain: 'pushnotifications-00001.firebaseapp.com',
    storageBucket: 'pushnotifications-00001.firebasestorage.app',
    measurementId: 'G-0PFD2NE2XF',
  );
}
